package com.quick.immi.ai.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Document {
    private Long id;
    private Integer userId;
    private Long caseId;
    private String identify;
    private String status;
    private String type;
    private String fileType;
    private String name;
    private boolean autoGenerated;
    private String createdBy;
    private String s3Location;
    private Long createdAt;
    private Long updatedAt;
}
