/*
 * This source file was generated by the Gradle 'init' task
 */
package com.quick.immi.ai.model;

public class LibraryNew {
    public boolean someLibraryMethod() {
        System.out.println("test");
        return true;
    }
}
