/* (C) 2024 */
package com.quick.immi.ai.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Document {
  private Long id;
  private Integer userId;
  private Long caseId;
  private String status;
  private String info;
  private String identify;
  private String type;
  private String fileType;
  private String name;
  private String description;
  private String createdBy;
  private String generationType;
  private String s3Location;
  private Boolean autoGenerated;
  private Long createdAt;
  private Long updatedAt;
  private Boolean manualOverridden;
}
