/* (C) 2024 */
package com.quick.immi.ai.dto.common;

import com.quick.immi.ai.entity.Identify;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DocumentDto {
  private Long id;
  private Integer userId;
  private Long caseId;
  private Identify identify;
  private String status;
  private String type;
  private String name;
  private Boolean autoGenerated;
  private String generationType;
  private Boolean manualOverridden;
  private String createdBy;
  // downloadable url
  private String presignUrl;
  private Long createdAt;
  private Long updatedAt;
}
