version: 0.2

phases:
  build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - sam build
      - sam deploy  --image-repository 471112972897.dkr.ecr.us-west-1.amazonaws.com/i94-download-task-lambda
