/* (C) 2024 */
package com.quick.immi.ai.dto.request;

import com.quick.immi.ai.entity.DocumentType;
import com.quick.immi.ai.entity.Identify;
import lombok.Data;

@Data
public class ListDocumentsRequestDto {
  private Long caseId;
  private DocumentType documentType;
  private Identify identify;
  private Boolean autoGenerated;
}
